import { Righteous } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/export-components";
import StoreProvider from "./StoreProvider";

const righteous = Righteous({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-righteous",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${righteous.variable} antialiased`}>
          <div className="h-dvh flex flex-col w-full">
            <Header />
            <div className="flex-1 overflow-auto">
              <div className="h-[calc(100%-160px)]">{children}</div>
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
